version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oil-erp-web
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=mongodb+srv://ahmed15ayman7ahmed2002:A123654789a@cluster0.o5nfq.mongodb.net/oil-erp?retryWrites=true&w=majority&appName=Cluster0
      - NEXTAUTH_URL=http://localhost:3005
      - NEXTAUTH_SECRET=eVms6JjbyXBHbYEl656bUIlWrZlShiLM9q9OPRsGXfU
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
      - prisma-studio
    command: >
      sh -c "
        sleep 20 &&
        npx prisma generate &&
        npx prisma db push --force-reset &&
        npm run dev
      "

  redis:
    image: redis:latest
    container_name: oil-erp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oil-erp-prisma-studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=mongodb+srv://ahmed15ayman7ahmed2002:A123654789a@cluster0.o5nfq.mongodb.net/oil-erp?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "
        sleep 25 &&
        npx prisma generate &&
        npx prisma studio --hostname 0.0.0.0 --port 5555
      "

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  redis_data:
  # mongodb_data: 
